---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    webhook: AgAYTeUpxUb8+dG4DTLqlkj17f3MDQQhe7HcYMY3EkC40iwW94Ep6jLXf4i6w48RqCpFsUAUqVmR8avIFipo7wS/olgJXQEkyY1dX61s9Nm4jhVu4NeAZ5UgeqZmF4/dlYKpZYKi5OqlRD0MZxXmb46ct68mjsmVqlUbnOeRkcH/ogC5CZdFqrVUEW5BlnAynFD1Vlm8iHyXlp6z/z8gC6DZN5rICYMc76fCw5JkZOlk/1nzqtOFgy5oi2TTWCLYWdNkE+f5/K7GaCBhpv9QWziMvYuGeYOyn1eKRjQofM6dfsXzF/krHkZSUBmBm5E5ib9N9RygN7LK4vkaPrsiYtxj5NaJ/I2TTJ5RsW/w1Qxa1KWMtOPVe4tMRoUAsX93nYeqD8dVGa/TUg1HHkpjHuPbmUHK4+KGOtkb1HdDEA5vbMGA6bCYctxQcEFuAL27qeiTWKT37HsKcznrTMeZBEZLHNw6YIfDwvTDJHTD+RU8Ve5hFha8U4xkRjDFBezrGAwN6lpmdRjHS0nG+WMsSXSPrH3hLJ/Vi2heVGF20NB4CWil0KC++wCzBBH+NL2dR8yWoVLH6SJ+m00/zkNwgKu9z5nUSHjbvtS3HIAbXC1a8jvu2ClRGIyBYGASa90mFAj/AU7G/alVR8ypCIQDxtnE59q3zTH82GbOH/BiwE3bpcb4ScRhG30jnQoUWmDPZEGvSzOjJyJ0jN0t9SgokDvZ3+BauiP6Ut0aUAuR6tqaAQmtBwF9DjUyc5n97eSPzl72wbWTRNpktZBrDETB9ku5fTD+jFlWh6aI6Ily82VyJvQ=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack
      namespace: monitoring
    type: Opaque
