---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    webhook: AgAj5a0XzcDl2cmyNdovtGu54J5snnCplO90oVoDPJOFNyvUdIZ5ANliTMySnuzFYNWAgl8yxvK6EqycYpLSV6kD/r0yf++PCrJ04vwR6ZRuh38nl2FRL+0TKnml7wwOUTCSP85HtJDEon4YzV5YKPqmu8xCQBfrCeF0Pwk6EDw3ZC9u3Yo4rnhWyQg3O1WU2g/ZmaP08vXJwz1ORIFC0yozkxBYXubj36aqdzAkeD2nToW5l4w/L5ErzBq+zdpbYOYsgJORES/3W3TaukOGSZQQrcV0ZfkNgA86FUr4nTAKvM8GdH/UKKy9eDlNLa3RgDUEoQdFXyBeOTYmOddFHaKawq3FeZpGHeE4Z6Eq3mBq+qexz/2TGRGdrkByP2ZMS93kSKNWzQSQpuzAT5eWWewUfsULNZR5jE4PgpCGZxLv/wUD/0hhdMHa/hnjYrU2Gz4sdE8TxJcQwCg1k42MMXLjzlVcOdFwmRx2zGRj7d5nkWnYz58mEl87JigEFN98/tmjPOW5GllkeixhAxb2LZpO9d4KRXSFC+O/MUT1e6nqAXu681WjEKZiyJHfqOCRYqYbCAWAmB6bkaGkkB5EAuyN96hWUL3SmPF08ObsXKIKQ36MA2+hna3WQqDSWhohsaXwULoKC1NPOLRD2pVbel6hGuCbk5ohPLC3lSNi/d3updnb3V7fKS/3k4eDAIEnLjk8q2D/Xfzm8YcD2jJLDpyTXn2iR2KOcI42EZFSUdMlIv69RI5c3nVaLnY/VYveN0eqRa0XOil+EO5IfPMmePVPF6kNDEGy3WGLgJWRHnFf0Y8=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack
      namespace: monitoring
    type: Opaque
