---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    webhook: AgCwNaOUUWllJo2LlL8memJl3TNmfVglqEDD5s21NMWntPE22AVb2W4Mty0jufvXVyNLxbVbLm/HxBnzYN1DT62QwPLlQz7xrX9ll5Jiw9gxo6RWYsPJoVtltDK+vkL6Y43tDpryOQUg+3zsh0yp7YVqEg2/+XZaaZGrFB25DAYgaX2mbdmKv3N8aNr+FJ1zW1EZtR2UNrTPli5IzeAT0W0k/b5lYuvhtUMsXJ4JZ/Ry18dWe4A80dD5Z6WLy3E9r4ldL+7ssS35Y3jXW4bGr+b3sCvlOePi3XK3Gfqr0Ke6031E+Vu+m98tMdgQgrY9d4zcVc+a7BgaMHScfYVwdviLXSEfaV5wSWBgJ4TRKh6MvGBH9gHvcJcij0LxdrmCsZgpTHvU2oMCsf8JsCN9rOuyYpHAKRpd7/ZXjWRFTv4oVWINkeGqHwB0/CKNKuM2+yv/Wykn5bZUhnP5Y5i37eoFbvFfeMuaemoWLZwT68PopyFUHgS5k/uD9ZYWe+4QrKagXfrDO6GU5gWeBLWw2SkJu3cFD/VvNd5kcA4l0y674mjQ9YFWKsey5iNM9kodSS8E5Bg53dH9tRnYF1n1lhhAuC0fEo9brIDKrdjf7qnWXVzIVNieSuyu33SUAcvnLGYvdyb88HEGoR/HTi2Or7HGeGe/Qv1Z+t83MA4nu6DcDbS9BxVztRi8njZxCidKHb2yS0g7ZXxVEWoO9jZCMCW2QegLvP5FD9hPMAAtn90pnccg3WMy0glh4ZaABZvgbSJWuD/Tfiz+wyr9+DzqbiHt1/2althSKvpdcFsM4Oz87Go=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack
      namespace: monitoring
    type: Opaque
