---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secret
  namespace: finbot
spec:
  encryptedData:
    GATEWAY_API_KEY: AgCYcdRyKt77oocbWOED3iucn9GpNquI6gtgDumxK6swan3dK7jG3cnhkzyhqtlVLgLlGZzbTLrTCxNCJw6gHFfufX18R7iSoihob4nzHKHDUlKBhM1Jey6INsPf1OhMl8MZarh21tE4FEn9XUvEebTijP42c4AhI+B64uEzyilfmMaKDM+uECp122Gt/Y0/Cx/oFxOj2W5z0YucdvF64PjdSinuRYNhSzj2NcPKWg2OcLRelt+jSKEPV5Ayqx4ujFgsprKyinfYlTqTs62bH6uSb/vigEAIfLwu0Z6D+hZ8t57j7eClWdfnBqL+650/NyFfI6ZQ0VB8EsjpVD3AHvPaiEbePZW9u467aTuJMnqQlC0X/92SO4kJJvWD08Tc7Eo5y8PMf3yw1dQaQV2phO2Hh2I8nGYQBe0zTI5APfcd593xprknb5rl10vgfHXmXlGCPoriW0sG7DD63qSDcBgi4FcL57NKMNzMEyrXygrwvHSDf6HBramHQOLsqQJBbDGFveMzQaSi5i7aUS6GapPWY3RGNip6XMwRpvAA2sL3LS2GYidIZjNqEZYwATp0v4odbh8kVMwGpD5ijP3TVmfYwMwKPaCXkd7ohZem7JoVXCfAqcZmpqQv0czh6C2ENXyjJUB+sH88+Oqny44y2YPsADmER56gIZCwM4OiyffaRozUrDVOT1BWEKCrQgzwIdkdFj05qaxn
  template:
    metadata:
      creationTimestamp: null
      name: gateway-secret
      namespace: finbot
    type: Opaque
