---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secret
  namespace: finbot
spec:
  encryptedData:
    GATEWAY_API_KEY: AgCRH5xCeni60JIwf9UfF4ZKFpcNqimSDK9FCod9i3EINzee4VtWa87b2iW4+EznI8UQgKobWh/3emNKd4dF6hPQ996d6Q06OXX8FLRSvf7E9DPobqiCKPv9jbXczfawO4ClAUq6SxFE00LUrMD3on0KyZkOAS3NDJkEzacCjalyF3e5ydKCVusY+uUaKNu6VCK1mBIjRCaP05zOEzPOq6iq2ZE+PBUs7Ep8+NMegePTvMrUR5Vq0W/vbfESpVJ1Ex94N6Vc2vdAS3VX0EesahupCi9nFV5lJrd4hpE9Pc3X5prh5G8FAg7vtcrV0FXVzXxF2hcXM/QMtC0fxx2BKmNgVOGJS52n7DQT2tqvMBZ4LyrIjzA92xkyXSnrtUHnjH5kmClP2FzdGT+sCzZ6QOTmD4LeBUjisCdLEy0DgJt1y5MStBN9g6jm/8TSxwTN7H5+g708l0shLHzZGA3rywY7gXByUWlf1wDBbAHCmhILN4whxAsKLMyqdhKtpHRhl9F2SslF+lzHFvIDcjNFXCQdpZfUvt028PBkc95g5jL5rb9WWqG4R2d8w3o9rlpeWiKlwl8+aAf3Cos3Xx5IhPzN7lSosizf2Gdk4rhTYWLdRv4NfCB8jA9L9KlMCO+tdewzRg9NYSKU32qJxIsjyc9v8dlLITlwuRVUy9w5WzE/dObiXfG17o81UzWKMHcCRaUxlxC4tvab
  template:
    metadata:
      creationTimestamp: null
      name: gateway-secret
      namespace: finbot
    type: Opaque
