---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secret
  namespace: finbot
spec:
  encryptedData:
    GATEWAY_API_KEY: AgB8p+NHLT3iDihQKxBUJYgUQKmbnNtpQ679dozZ/rUIBPvtBTuVX5pXi5n3zMeENOExVxqUUzCIaTFtRHkCTGKRNPv7XKCUn4EETfh61fylIdzyvWRbG+raNnYp5gegf9fgQo1C1QGUo7lAVA8kBcZuDVyrRuIkkAPjYOA6Yzlf1FL5x0f6nejxqLrILWXxv6fyd4zWIrZFV4hunSU1Yk8DxcA6isDrNWWp96DHfvQuzZx/iC4LMQUZnWl8aATHKNYFoIkNfDctWo1vYE4NeNZN21LQZ8YOpDWZWuCxpNZVGsFJPXcgSbpiheI1VtQP6SEBH2+I9vbnjWNB+Oof1iT7qN/8e+ub+D78AtzQSQuRWtZzJ5cmjBNtsoh1nq28inwDx5fE1jHg49Z8x2TAmIFyqvFNcd6szqZ31R4DtUptSIxhJAszK813mvaLAr08OYu8YTZaRQ+9eu8bX7ovBWCrigRzBNLtgxL8/v0ySGMDrvOjnoWhlppz0AEtI9xeADsDZbh4tqf1XR63uI+kY3zkbHAq4zU7LCZxLz87cWYUp0o8MBA238Dm8f+18IbM7AfJvwmLTpe8ughpbFSycyrdFMUjFKjI4NoqmGpC2ny2ZBubOLXAcizqtVsMV75quxvrvfngWz5r5HMz3sBGqjLdZT/ceLCjGi9wGO2/wdvLKwzDdgi7uG4rVNIUE0rgMRsCAXjI68pX
  template:
    metadata:
      creationTimestamp: null
      name: gateway-secret
      namespace: finbot
    type: Opaque
