---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: model-secret
  namespace: finbot
spec:
  encryptedData:
    HF_TOKEN: AgCg9f520a4dYcAVLg7ZmB7MA4Mdai0TbDA1BFk96bL1hcsMS/O2O9saq7PFEAobejSn2qBsRVUDUzGVDt8+bFJhVD/znGDzEghg6Zmu6VNjcOoLpipTYtgJYpAVwr/3I7AIchj4TMEaxNNb7Js5Wf10yaK2EBh+MIdNTyxabRJd9p41bft8/8Wv/SpNUS9Xny47QbyYmXDootzXsrf8+trH7cq+55KsRHyB/C3WWQgh67gERoqG4ljO4gOMv3aNXp9UPI7zp2rLu+NOEYs68SRNstruWjj2WCbPXH2dgH+6rde8AYVicBFX3mM3GkcF8qymd9m3f2lpF8rUV4Az/3fg5r80F4FvDtlJDONGDyNaeYv5SPvUrRUYm4nd2vKozEuHIi9TofsKeMArWUeXVGlpwZ9fVLA0GMJxsHoId83YlM9rSP2p2ORFyyeX3vppOkuTNYPRYsQ0UVe7bYPTDWyf0X1JjglDLBs9T/lCGeKC+McsT3rYloasHdKfx+/+HDiu4HECuKXcczsYL48jR9R2Aw4FpAjTOHSRmytkZEBxS+bTqIQlEn/+WCrpdif1kFU7fdrFHBDtYF6naleksQLBIFmBE3H4vhALmjdfWGmkrFaEFxPHxHVrxi4nJUX7kE3f65xBtm3R+4hkt3KLTiUaH9ZUq5AqsxqVejGAN9DRLHJRlYnka3rK3upisNnhjqW2CN2SBIlDAS+kEzEpDqogfkS6wSdZJgfeKZc4e4IX0ZTKbFrA
  template:
    metadata:
      creationTimestamp: null
      name: model-secret
      namespace: finbot
    type: Opaque
