---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: model-secret
  namespace: finbot
spec:
  encryptedData:
    HF_TOKEN: AgAOq50ZGGU0AAf/LmY0oICYP4UhXk6bOGeqYrp0y5dCIKst1ueXt1RSmc9yAi4eFsnepu8K/OmYiFMNKU1pKd2S0sm0t4CpEAMFtN+8/SUYaHx+aVaMmaoishc+cqlnMmZNoewMjYsj7rnhfZjEK6pUW0I9VPvMo66BqZ93g3kYq6ukW1Y84dTja2TaH3iwa5N5Ls+WymEBh2Dr6WR2/aiSVmfgUHt2fMUDFiFwVpFVsVnRNiz67cMaGqu0/LsMWyYoRxzOPzfKApjglvjSYa8wKAY47FENk4XrABEvZBLEYkD6X5y/wVDzmJFVp7xY9wFzF8oeujSDhWw+MkkQawh1wnhI580d9HwSLB4h5zMxB+wG5izXT8Ohi7s6omENw4/O5QV9uVtQvHlOoZ19KYihne2XTFkebpD6aXu1h7bs6zxrlqZbIk9Q3Mwjk12zu1nu02rplKs6qSHpxlhTGKrDrPVMdlWT3hsxf6576+x1wwlsCIqD+sVGgV15IKDUPys/E89ftPLLh7hQlxdcVxyCWognwtANINrFv9qUPLJE6PHlPUaMooVUBuPdKnSKLUD7vjkYhLbL1wOuJ7oKwQe2+Sbd+xFIkmFzmZAZ7F5Wcji1rZ0EuFMsUocRINAAaASPE10kMGIpdZl44UnG+LGbFi685RoEp7QdbNPnM419Vlvv12FB6ZC73POTq3RIvYPf6XFhIhGYB1jhexw3bAsep6u4EpCbhxy0mpZnYxSkJBbdWMCo
  template:
    metadata:
      creationTimestamp: null
      name: model-secret
      namespace: finbot
    type: Opaque
