---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: model-secret
  namespace: finbot
spec:
  encryptedData:
    HF_TOKEN: AgBgz26CGlY9xYeiTbx2pNu4hTqxBW5iOwH9G44Siqr1v1/gxZYvvsaL/jVoAFCzsJ1AFHsIqidpE0wqgh02cyCqlsoGTur/nok88WZjpcrPD38BVOMreOfUR00vCZVpYQynXJfvJUTqGStLVNdhHeGPHjiqYXf2OSGIMn1c5GbhHVsgs/DuIiHsxDameOGm1eGu8lCGkZzP0UNw9HgxgNZZm/KA5GJ3D4SYS5WpLi4Wwlvju1cZRYEJlWNIYaAuR5lCWpDdqbei4PYGK31o5RDVnZdip8f/qMbS7GABvg55a2goVWnH3pRNdlw7SO6Sxirx0QhCeox4/Xr6uIqis9j9jEek1w4K9CYEMwZVoNa2s0xgMxdomLwKrmOiyk1KDCU09Hh7Vaaxq3nGZenH1L8LeCzCNnIWtnvCoj+KSR21Ji7dYzpe0TXN61lQoiSyHDz4FdzhHRR6ZlBZFNw4VN2D5+jm+qsCmNWaarUz0EaKJ3z55T/PCdsq906y1Ckyu+wOA+gpBHPz1RSzK2a53afLlY95i/ls80NmXajpRQM4Tbc26joIeqzskmVBwvgzlYFa4Iv9s+XAbmc/lgfpI9xazQs9fNtcoE+w85aVTorXehoD/6rCULjI534w75dki6iJqTyuDR3U8MEb4nc2A6P50Lxci/RQm3JVGSwzHBaisfofXeTDOO9Qkx8wvcAAqZ+JXrHvbr7EnH4nFknU3RWuWu2tJbYKo/OnhVtPFZznpT00M8Jo
  template:
    metadata:
      creationTimestamp: null
      name: model-secret
      namespace: finbot
    type: Opaque
